FROM certbot/certbot

WORKDIR /

RUN wget https://releases.rancher.com/cli2/v2.7.7/rancher-linux-amd64-v2.7.7.tar.gz && \
  tar zxvf rancher-linux-amd64-v2.7.7.tar.gz && \
  install -o root -g root -m 0755 /rancher-v2.7.7/rancher /usr/local/bin/rancher

RUN wget "https://dl.k8s.io/release/v1.25.16/bin/linux/amd64/kubectl" && \
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

COPY scripts /scripts

WORKDIR /opt/certbot

